### ISSUE TITLE
Implement per-zone ToDo's

### ISSUE THREAD

**Issue by jantman** [jantman/gw2copilot#9]
1. Need UI (modal popup - see [bootleaf](https://github.com/bmcbride/bootleaf/blob/f50fc448fb9d7c0c3ae2d099aacb7316a5f2534b/index.html#L230) for an example) for managing per-zone ToDos. Remove/edit existing ones; add new ones based on a list of zones and a text box input. Needs to be stored server-side.
2. Display these in the sidebar. They should be able to include HTML.

**Comment by jantman** [comment]
For editable tables: [appendgrid](http://appendgrid.apphb.com/Demo) or [DataTables Editor](https://editor.datatables.net/)

**Comment by jantman** [comment]
This should have some sort of eye-catching animation when it changes.

**Comment by jantman** [comment]
The UI side of this for editing reminders is done as of 6d68cb6d6ac7c6db31dd5330d785f2c880eac866

Just need:
- [x] API to set/POST reminders
- [x] API to GET reminders
- [ ] hook UI to API for get and save
- [ ] UI to display reminders in sidebar, with animation
